#!/bin/bash
cd /usr/local/
mkdir sadRick
cd sadRick
mkdir images
cd images
wget labcomp.cl/~vlizana/rickWallpaper/thumb{001..180}.png

cd /usr/local/bin
wget raw.githubusercontent.com/vlizana-gh/feelTheDesktop/master/setbg
chmod u+x setbg

crontab -l > tempCron
echo "* * * * * /usr/local/bin/setbg" >> tempCron
# if you want you can set the change every 8 minutes instead of every minute uncommenting the line below and commenting the line above.
# is set to every minute by default because if you close your laptop in the night and open it in the day it only takes up to a minute to update.
#echo "*/8 * * * * /usr/local/bin/setbg" >> tempCron
crontab tempCron
rm tempCron

feh --version >> /dev/null 2>&1 || echo "If you're not using gnome or macOS do not forget to install feh"
