#!/bin/bash

home=/usr/local/sadRick/images
picture=$(( ( (`date +%_H`*60 +`date +%_M`)/8 +37) %180 +1 ))

if [ "$(uname)" == "Darwin" ]; then
	osascript -e "tell application \"Finder\" to set desktop picture to POSIX file \"$home/thumb$(printf "%03d" $(( 10#$picture )) ).png\""
elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
  export DISPLAY=:0
  case $DESKTOP_SESSION in
  gnome )
      gsettings set org.gnome.desktop.background picture-uri "file://$home/thumb$(printf "%03d" $(( 10#$picture )) ).png"
      ;;
  * )
      feh --bg-scale "$home/thumb$(printf "%03d" $(( 10#$picture )) ).png"
      ;;
  esac
fi
