#!/bin/bash

# for when you want to test a picture
home=/usr/local/sadRick/images
picture=$1
export DISPLAY=:0
case $DESKTOP_SESSION in
gnome )
    gsettings set org.gnome.desktop.background picture-uri "file://$home/thumb$(printf "%03d" $(( 10#$picture )) ).png"
    ;;
* )
    feh --bg-scale "$home/thumb$(printf "%03d" $(( 10#$picture )) ).png"
    ;;
esac
